Systrotech.Blog/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Systrotech.Blog.View_Models;
using Systrotech_Repository.Entities;
using Systrotech_Repository.Services;
using Systrotech.Blog.Helpers;

namespace Systrotech.Blog.Controllers
{
    public class QuestionController : Controller
    {
        BlogRepository blogContext = new BlogRepository();
        int pageSize = 10;
        // GET: Question
        public ActionResult Index(int id)
        {
            int userId = Convert.ToInt32(HttpContext.Session["UserId"]);
            ViewBag.userId = userId;
            var question = blogContext.GetById<Question>(id);

            #region GetLastPage
            if (question.Comments.Count() % pageSize == 0) TempData["PageCount"] = question.Comments.Count() / pageSize - 1;
            else TempData["PageCount"] = question.Comments.Count() / pageSize;
            #endregion

            try // ete delete em anum u pahum em url exceptiona gcum 
            {
                ViewBag.questionUserId = question.UserId;
            }
            catch (Exception)
            {
                return RedirectToAction("Login", "Account");
            }            
            int qCount = blogContext.SelectAll<Question>().Where(p => p.UserId == question.UserId).Count();
            return View(new SelectedQuestionViewModel { Question = question, QuestionsCount = qCount, SortByCommentList = Helper.SortCommentList });
        }

        [HttpPost]
        public ActionResult Comment(SelectedQuestionViewModel model)
        {
            int userId = Convert.ToInt32(HttpContext.Session["UserId"]);
            ViewBag.userId = userId;
            Comment comment = new Comment { Comment1 = model.Comment, Datetime = DateTime.Now, QuestionId = model.Question.Id, UserId = userId };
            comment.Question = blogContext.GetById<Question>(model.Question.Id);
            comment.User = blogContext.GetById<User>(userId);
            bool save = blogContext.Insert(comment);
            return RedirectToAction("CommentList", new { questionId = comment.Question.Id });
        }

        // [HttpPost]
        public ActionResult Search(string searchTerm)
        {
            return View(model: searchTerm);
        }

        public ActionResult SearchByCategory(int id)
        {
            return View("SearchByCategory", id);
        }

        public ActionResult RightQuestion(int categoryId)
        {
            IEnumerable<Question> questionLists = blogContext.SelectAll<Question>()
                .Where(p => p.CategoryId == categoryId)
                .OrderByDescending(p => p.Datetime).Take(5);

            return PartialView("_RightQuestion", questionLists);
        }

        public ActionResult CommentList(int questionId, int sortBy = 1, int page = 0)
        {
            int userId = Convert.ToInt32(HttpContext.Session["UserId"]);
            ViewBag.userId = userId;

            var comments = blogContext.GetById<Question>(questionId).Comments.ToList().OrderByDescending(p => p.Datetime);
            
            #region GetLastPage
            if (comments.Count() % pageSize == 0) TempData["PageCount"] = comments.Count() / pageSize - 1;
            else TempData["PageCount"] = comments.Count() / pageSize;
            #endregion

            if (sortBy == 1)//by date
            {
                comments = comments.OrderByDescending(p => p.Datetime);
            }
            else if (sortBy == 2)//by right answer
            {
                comments = comments.OrderByDescending(p => p.Correct);
            }
            var finalData = comments.Skip(page * pageSize).Take(pageSize);

            return PartialView("_Comment", finalData);
        }

        public ActionResult ChangeComment(int commentId)
        {
            var comment = blogContext.GetById<Comment>(commentId);
            comment.Correct = true;
            bool change=blogContext.Update<Comment>(comment);
            return RedirectToAction("CommentList", new { questionId = comment.Question.Id});
        }
        
        //for autocomplite
        public JsonResult GetQuestions(string term)
        {
            if (!string.IsNullOrEmpty(term))
            {
                try
                {
                    var searchlist = blogContext.SelectAll<Question>().Where(x => x.Title.ToUpper().Contains(term.ToUpper())).Select(p => new { value = p.Id, label = p.Title }).ToList();

                    return Json(searchlist, JsonRequestBehavior.AllowGet);
                }
                catch (Exception)
                {
                    return Json("There are not !!! ", JsonRequestBehavior.AllowGet);
                }
            }
            return Json("There are not !!! ", JsonRequestBehavior.AllowGet);
        }
    }
}

Systrotech.Blog/Views/Question/Index.cshtml
@model Systrotech.Blog.View_Models.SelectedQuestionViewModel
@{
    ViewBag.Title = "Index";
}

@{
    var currentPage = Convert.ToInt32(TempData["PageCount"]);
}

<div class="col-md-10 col-lg-10 col-sm-10 col-xs-10">

    <div id="questionContent">
        <p><b style="font-size:30px">@Model.Question.Title</b></p>
        @Html.Raw(Model.Question.Content)
        <hr />
    </div>

    <div style="height:50px">
        <div style="float:left">
            <span><b style="color:darkorange">Sort Comment by </b></span>
            @Html.DropDownListFor(x => x.SortByComment, new SelectList(Model.SortByCommentList, "Value", "Text"), new { @id = "SortByComment" })
        </div>

        <div style="float:right">
            @if (ViewBag.userId > 0)
            {
                AjaxOptions options = new AjaxOptions { OnSuccess = "success" };

                using (Ajax.BeginForm("Comment", "Question", options/*, htmlAttributes: new { @id = "frmComment" }*/))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group " style="float:left">
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Comment, rows: 2, columns: 80, htmlAttributes: new { htmlAttributes = new { @class = "form-control " } })
                        </div>
                    </div>
                    @Html.HiddenFor(model => model.Question.Id)

                    <div class="form-group" style="float:right">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Add" class="btn btn-default" />
                        </div>
                    </div>
                }
            }
        </div>

    </div>

    <hr />
    <div id="comment">
        @Html.Action("CommentList", "Question", new { questionId = Model.Question.Id })
    </div>


    <div style="text-align:center">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#" onclick="comments.Browse('first')">First</a></li>
                <li class="page-item"><a class="page-link" href="#" onclick="comments.Browse('prev')">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#" onclick="comments.Browse('next')">Next</a></li>
                <li class="page-item "><a class="page-link" href="#" onclick="comments.Browse('last')">Last</a></li>
            </ul>
        </nav>
    </div>

    <div>

    </div>
</div>


<div class="row col-md-2 col-lg-2 col-sm-2 col-xs-2" style="background-color:#d9edf7">

    <p>@Model.Question.User.Surname @Model.Question.User.Name </p>
    <p>Registerd in: <br /> @Model.Question.User.Datetime.ToString("MMMM dd, yyyy")</p>
    <p>Pass  @Model.QuestionsCount  Question</p>
    <hr />

    @Html.Action("RightQuestion", "Question", new { categoryId = @Model.Question.CategoryId })

</div>

<script>
    var questionCommentList = '@Url.Action("CommentList", "Question")';
    var questionId = @Model.Question.Id;
    var currentPage = @currentPage;
</script>

<script src="~/Scripts/MyScript/Home.js"></script>

<style>
    .commentstyle {
        min-width: 330px;
    }
</style>

Systrotech.Blog/Views/Question/Search.cshtml
@model string


@Html.Action("Home", "Home", new { id = 0, categoryId = 0, searchTerm = Model })

Systrotech.Blog/Views/Question/SearchByCategory.cshtml
@model int?


  @Html.Action("Home","Home", new { id = 0, categoryId = Model })

Systrotech.Blog/Views/Question/_Comment.cshtml
@model  IEnumerable<Systrotech_Repository.Entities.Comment>

@foreach (var item in Model)
{    <p>
        @if (item.Correct == true)
        {
            <label class="btn btn-success active">
                <span class="glyphicon glyphicon-ok"></span>
            </label>
        }
        else
        {
            if (ViewBag.userId == item.Question.UserId)
            {
                <label class="btn btn-default">
                    <input type="checkbox" onchange="changeComment.correct(@item.Id)">
                    <span class="glyphicon glyphicon-ok"></span>
                </label>
            }
        }
        @item.Comment1  <span style="color:forestgreen">by @item.User.Name</span>
    </p>
    <hr />
}

<script>
    var questionChangeComment = '@Url.Action("ChangeComment", "Question")';
</script>

Systrotech.Blog/Views/Question/_RightQuestion.cshtml
@model IEnumerable<Systrotech_Repository.Entities.Question>

@foreach (var item in Model)
{
    string title;
    if (item.Title.Length > 40)
    {
        title = item.Title.Substring(0, 40) + "...";
    }
    else
    {
        title = item.Title;
    }
    <div class="rightQuestions">
        <tr>
            <td>
                @Html.ActionLink(title, "Index", "Question", new { id = item.Id }, new { @class = "" })
                <hr />
            </td>
        </tr>
    </div>
}